### ISSUE TITLE
Consider adding the MIT license as an option

### ISSUE THREAD

**Issue by brson** [ruuda/thread-id#5]
I know it's super annoying to receive bugs about licenses. Sorry 😞 

Since thread-id provides quite a fundamental feature, it is used widely, and being Apache only makes it slightly incompatible with Rust's dual license, because Apache imposes more restrictions than MIT. The standard library, for example could not take thread-id as a dependency. Crates that could reasonably considered part of the Rust 'platform', and e.g. could be conceivably be distributed with Rust, or perhaps required by a wide subset of Rust's users, are ideally fully compatible with its license. [Here's some further info](https://github.com/brson/rust-api-guidelines#crate-and-its-dependencies-have-a-permissive-license-c-permissive) about this situation.

Rust is actually already distributing thread-id as a dependency of mdbook, and is considered a [license exception](https://github.com/rust-lang/rust/blob/master/src/tools/tidy/src/deps.rs#L27) in-tree; but to use thread-id within the runtime components of Rust would require a different license.

**Comment by ruuda** [comment]
I have reasons for not dual-licensing my code, but for a crate that already spends 6.8 times as many bytes on the license text as on source code, I am not going to make a fuss about it.

> and is considered a [license exception](https://github.com/rust-lang/rust/blob/master/src/tools/tidy/src/deps.rs#L27) in-tree

The comment there is wrong though, this crate is currently Apache 2.0, not MPL.

**Comment by ruuda** [comment]
Fixed by cd036490bc088083fbb31c648a6196729f7e4c05. I’ll also make a new release so crates.io has the right metadata.

**Comment by ruuda** [comment]
@test9753 @Amanieu as you have both contributed to this crate, I should have obtained your permission before doing this. Are you ok with this change?

**Comment by Amanieu** [comment]
I'm OK with this.
